BEAC-332 Insert placeholder paper doll
alucioinc/twilio-video-app-react pull request #10
Opened 2020-09-06 12:00 UTC by chibchombiano26

<a href="https://www.loom.com/share/e4ee0b3aa2c2458e805e43a442c9f4b2"> <p>6 September, 2020 - Loom Recording - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/e4ee0b3aa2c2458e805e43a442c9f4b2-with-play.gif"> </a>

2020-09-06 12:00 UTC, chibchombiano26 commented on alucio/components/LocalVideoPreview/LocalVideoPreview.tsx
> +import ParticipantMeetingPlaceholder from '../ParticipantInfo/ParticipantPlaceholder/ParticipantMeetingPlaceholder';
no alias yet for twilio video

2020-09-11 14:36 UTC, alucio-echen requested changes

2020-09-11 14:36 UTC, alucio-echen commented on alucio/components/LocalVideoPreview/LocalVideoPreview.tsx
> +  console.info('test', videoTrack);
we should probably remove this log

2020-09-11 14:39 UTC, chibchombiano26 commented on alucio/components/LocalVideoPreview/LocalVideoPreview.tsx
> +  console.info('test', videoTrack);
Removed

2020-09-11 19:06 UTC, alucio-echen approved these changes

2020-09-11 19:06 UTC, merged