BEAC-417 - Share Screen
alucioinc/twilio-video-app-react pull request #14
Opened 2020-09-11 02:16 UTC by chibchombiano26

BEAC-417 - Share Screen

2020-09-15 16:23 UTC, chibchombiano26 commented on alucio/components/MainParticipant/MainParticipant.tsx
> -        enableScreenShare
if we do not remove this, the video screen is showed in the video of the host

2020-09-15 16:24 UTC, chibchombiano26 commented on alucio/components/ParticipantTracks/ShareScreen.tsx
> +  if (isLocal) {
on local doesnt show the share screen

2020-09-15 16:24 UTC, chibchombiano26 commented on alucio/components/ParticipantTracks/ShareScreen.tsx
> +  if (publications.some(p => p.trackName.includes('screen'))) {
this makes the trick of show the screen sharing

2020-09-15 16:25 UTC, chibchombiano26 commented on alucio/components/ScreenShare/PlaceHolder.tsx
> +export default function ScreenPlaceHolder(props:PlaceHolderProps) {
just the place holder, of sharing, for the host

2020-09-15 16:26 UTC, chibchombiano26 commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
> +    id: 'my_content',
to avoid, find the menu by title, because this could and change when the user select an option, mute/unmute etc

2020-09-15 16:26 UTC, chibchombiano26 commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
> +export enum PresentationMenuOptionsEnum {
to avoid using strings

2020-09-15 16:28 UTC, chibchombiano26 commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
>  interface HeadBarProps {
sorting the properties

2020-09-15 16:29 UTC, chibchombiano26 commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
> +interface ShowConfirmationInterface {
the modal that we need to show, when the user changes from sharing screen to my content and vice versa

2020-09-15 16:29 UTC, chibchombiano26 commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
> +interface ShowConfirmationInterface {
for sure this will change when we will have the dna component for this

2020-09-15 16:30 UTC, chibchombiano26 commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
> +function setSelectedMenuProperty(PresentationSelectedOptions: PresentationMenuOptionsEnum[], property: string) {
to set the blue and disabled states in the menu

2020-09-15 16:31 UTC, chibchombiano26 commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
> +    audioFiles,
sorting the properties

2020-09-15 16:31 UTC, chibchombiano26 commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
> +      return !(['My Content', 'Notes', 'Share screen'].includes(e.title));
disable sharing for the attendees

2020-09-15 16:33 UTC, chibchombiano26 commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
> +      case PresentationMenuOptions[0].id: // -> My Content
changes to the id, i have presented the idea before of change this to a record object, looks like the array is a little unorganized, probably we can do this in a following ticket

2020-09-15 16:33 UTC, chibchombiano26 commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
> +        if (!isMenuActive(PresentationMenuOptions, 'share_screen')) {
if the share screen is active, show the confirmation dialog

2020-09-15 16:34 UTC, chibchombiano26 commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
> +        if (!isMenuActive(PresentationMenuOptions, 'my_content')) {
same as above

2020-09-15 16:36 UTC, chibchombiano26 commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
> +  function onSuccess() {
when the user accepts the confirmation modal, we should trigger the actions, I have noticed that my content actions are a little bit confusing, probably we need to do a refactor over that

2020-09-15 16:36 UTC, chibchombiano26 commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
> +    setShowConfirmation({ ...showConfirmationInitialState, visible: false });
hide the confirmation modal

2020-09-15 16:37 UTC, chibchombiano26 commented on alucio/components/Virtual/Menu/Menu.tsx
> +      <Iffy is={props.menuOption.disabled}>
while the room is not connected, we need to prevent the share funcionality

2020-09-15 16:38 UTC, chibchombiano26 commented on alucio/components/Virtual/Menu/Menu.tsx
> +  activeTitle?: string,
when the button is active, the text could change, in this case, changes to stop share

2020-09-15 16:38 UTC, chibchombiano26 commented on alucio/components/Virtual/ShareContent/ShareContent.tsx
> +  text: string
we will remove the text after the user share the screen. so for that reason we need this property

2020-09-15 16:39 UTC, chibchombiano26 commented on alucio/components/Virtual/VirtualExchange.tsx
> +  audioFiles?: any[],
sort properties

2020-09-15 16:39 UTC, chibchombiano26 commented on alucio/components/Virtual/VirtualExchange.tsx
> +    audioFiles,
sort properties, we have a ton of them we need to refactor this component asap

2020-09-15 16:40 UTC, chibchombiano26 commented on alucio/components/Virtual/VirtualExchange.tsx
> +  const [isSharing, toggleScreenShare] = useScreenShareToggle();
detect if we are sharing our screen

2020-09-15 16:41 UTC, chibchombiano26 commented on alucio/components/Virtual/VirtualExchange.tsx
> +  const [showWelcomeMessage, setShowWelcomeMessage] = useState(true);
set the welcome message off if we already did an action

2020-09-15 16:41 UTC, chibchombiano26 commented on alucio/components/Virtual/VirtualExchange.tsx
> +  const [disabledOptions, setDisabledOptions] = useState([PresentationMenuOptionsEnum.SHARE_SCREEN]);
at this momeent only disable the sharing button, while the room is connected, but we can use this for the other buttons

2020-09-15 16:42 UTC, chibchombiano26 commented on alucio/components/Virtual/VirtualExchange.tsx
> +  const screenShareParticipant = useScreenShareParticipant();
detect if the user have a track to share his screen, it is used down below

2020-09-15 16:43 UTC, chibchombiano26 commented on alucio/components/Virtual/VirtualExchange.tsx
> +  const selectedPresentationOptions: PresentationMenuOptionsEnum[] = selectedMenuItems();
define if an element is selected, blue element in the meeting bar

2020-09-15 16:43 UTC, chibchombiano26 commented on alucio/components/Virtual/VirtualExchange.tsx
> +        setDisabledOptions([]);
when the user is connected we enable the options

2020-09-15 16:44 UTC, chibchombiano26 commented on alucio/components/Virtual/VirtualExchange.tsx
> +    roomState === 'connected' && toggleScreenShare();
an additional validation to connect only in the case the user is in the room. doesnt hurt leave it.

2020-09-15 16:45 UTC, chibchombiano26 commented on alucio/components/Virtual/VirtualExchange.tsx
> +              shareScreen={toggleShareScreen}
pass props to the meeting bar, other control that we need to do a refactor :)

2020-09-15 16:45 UTC, chibchombiano26 commented on alucio/components/Virtual/VirtualExchange.tsx
> +            <Iffy is={screenShareParticipant && !isHostPresenting}>
only share if we are not presenting

2020-09-15 16:46 UTC, chibchombiano26 commented on alucio/components/Virtual/VirtualExchange.tsx
> +                text={showWelcomeMessage ? 'Welcome To The Meeting' : ''}
defaul message, todo we can move this to a constant o a different file

2020-09-15 16:48 UTC, chibchombiano26 commented on src/hooks/useScreenShareToggle/useScreenShareToggle.tsx
> +        setIsSharing(true);
we need to identify as soon the screen share start, to do the change in the host for the place holder, otherwise we get a blink in that screen

2020-09-17 07:22 UTC, alucio-echen requested changes
Couple of questions otherwise looks good

2020-09-17 07:22 UTC, alucio-echen commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
> +  const sharedScreen = PresentationMenuOptions.find((item) => (item.id === id))
maybe pick a different name?

2020-09-17 10:33 UTC, chibchombiano26 commented on alucio/components/ParticipantTracks/ShareScreen.tsx
> +      isLocal={track.name.includes('camera')}
right, changed

2020-09-17 10:39 UTC, chibchombiano26 commented on alucio/components/Virtual/MeetingControls/MeetingControls.tsx
> +  const sharedScreen = PresentationMenuOptions.find((item) => (item.id === id))
changed :)

2020-09-17 10:43 UTC, chibchombiano26 commented on alucio/components/Virtual/ShareContent/ShareContent.tsx
> +  text: string
yeah the showWelcomeText was introduced by another pr, so I didn't notice this until I rebased my branch, although doesn't hurt have the ability to change that text

2020-09-17 10:49 UTC, chibchombiano26 commented on alucio/components/Virtual/VirtualExchange.tsx
> +  const [showWelcomeMessage, setShowWelcomeMessage] = useState(true);
thanks for pointing into this, I didn't notice this on my rebase :)

2020-09-17 10:49 UTC, chibchombiano26 commented on alucio/components/Virtual/VirtualExchange.tsx
> +  useEffect(() => {
thanks for pointing into this, I didn't notice this on my rebase

2020-09-17 15:17 UTC, alucio-echen approved these changes

2020-09-17 15:41 UTC, merged